title: 'Sturla Bragason'
author:
  name: Sturla Bragason
  email: sturla.bragason@proton.me

description: >
  Writing about some of the stuff I've been working on or thinking about, as time permits.

remote_theme: jekyll/minima

header_pages:
  - cv.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-spaceship
#   - jekyll-toc

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/sturlabragason" }
    - { platform: mastodon, user_url: "https://mastodon.social/@sturlabragason" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/sturlabragason/" }

jekyll_spaceship:
  mermaid:
    enabled: true

collections:
  my_collection:
    output: true  # This makes sure the collection is rendered as web pages
    permalink: /:collection/:path/
