name: Maze Generator

# Controls when the action will run. 
on:

  # Runs every month
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Delete current mazes
      run: |
        rm ./mazes/*.png
    - name: Run Maze Generator
      run: |
        python scripts/maze_generator.py
    - name: Update HTML
      run: |
        python scripts/update_html.py
    - name: Commit and push if it changed
      run: |
        git config --global user.name 'Automatic Maze Generator'
        git config --global user.email 'mazegen@no-reply.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update mazes"
        git push
